# Generated by Django 5.1.1 on 2024-10-03 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='photographer',
        ),
    ]
