# Generated by Django 5.1.1 on 2024-09-30 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_review'),
        ('photo_app', '0002_photo_description_photo_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolios'},
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('PT', 'Portrait'), ('LS', 'Landscape'), ('WL', 'Wildlife'), ('AR', 'Architecture'), ('FS', 'Fashion')], default='PT', max_length=2),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photographer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='photos',
            field=models.ManyToManyField(related_name='portfolios', to='photo_app.photo'),
        ),
    ]
