# Generated by Django 5.1.1 on 2026-05-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['category'], 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('WD', 'Wedding'), ('FM', 'Family'), ('LV', 'Love Story'), ('PT', 'Portrait'), ('CH', 'Children'), ('MT', 'Maternity'), ('BS', 'Business Portrait'), ('EV', 'Event'), ('FS', 'Fashion'), ('LS', 'Landscape'), ('AR', 'Architecture'), ('WL', 'Wildlife'), ('OT', 'Other')], default='PT', max_length=2, unique=True),
        ),
    ]
