# Generated by Django 5.2.14 on 2026-05-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_portfolio_options_alter_portfolio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
