# Generated by Django 5.1.1 on 2024-10-04 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_portfolio_photographer'),
        ('photo_app', '0004_rename_user_photo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='portfolios', to='photo_app.photo'),
        ),
    ]
