# Generated by Django 5.2.14 on 2026-05-30 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_portfolio_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.CharField(choices=[('WD', 'Wedding'), ('FM', 'Family'), ('LV', 'Love Story'), ('PT', 'Portrait'), ('CH', 'Children'), ('MT', 'Maternity'), ('BS', 'Business Portrait'), ('EV', 'Event'), ('FS', 'Fashion'), ('LS', 'Landscape'), ('AR', 'Architecture'), ('WL', 'Wildlife'), ('OT', 'Other')], max_length=2, unique=True),
        ),
    ]
