# Generated by Django 5.1.1 on 2024-10-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_portfolio_photos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
