# Generated by Django 5.1.1 on 2024-10-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Master', 'Master'), ('Client', 'Client')], default='Client', max_length=10, verbose_name='Роль'),
        ),
    ]
