# Generated by Django 5.1.1 on 2024-10-01 20:18

import cloudinary_storage.storage
import photo_app.utils.image_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='users_images', validators=[photo_app.utils.image_validator.file_validation], verbose_name='Аватар'),
        ),
    ]
