# Generated by Django 5.2.14 on 2026-06-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_image_user_avatar_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('client', 'Client'), ('photographer', 'Photographer')], default='client', max_length=20, verbose_name='Role'),
        ),
    ]
