# Generated by Django 5.2.14 on 2026-06-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_is_email_verified_user_updated_at_clientprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'verbose_name': 'Client profile', 'verbose_name_plural': 'Client profiles'},
        ),
        migrations.AlterModelOptions(
            name='photographerprofile',
            options={'verbose_name': 'Photographer profile', 'verbose_name_plural': 'Photographer profiles'},
        ),
    ]
