# Generated by Django 5.2.14 on 2026-06-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_clientprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoritePhotographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_photographers', to='users.clientprofile')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_clients', to='users.photographerprofile')),
            ],
            options={
                'unique_together': {('client', 'photographer')},
            },
        ),
    ]
