# Generated by Django 5.2.14 on 2026-06-24 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_country_options_remove_country_code_and_more'),
        ('users', '0007_favoritephotographer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='preferred_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_preferred_profiles', to='locations.country'),
        ),
        migrations.AddField(
            model_name='photographerprofile',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photographer_profiles', to='locations.country'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='preferred_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_preferred_profiles', to='locations.city'),
        ),
        migrations.AlterField(
            model_name='photographerprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photographer_profiles', to='locations.city'),
        ),
    ]
