# Generated by Django 5.1.1 on 2024-10-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Title (optional)')),
                ('description', models.TextField(blank=True, null=True)),
                ('public_id', models.CharField(blank=True, max_length=255, verbose_name='Cloudinary public_id')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='Cloudinary Image URL')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публічне фото')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')])),
            ],
        ),
    ]
