# Generated by Django 5.1.1 on 2024-10-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0002_photo_description_photo_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
    ]
