# Generated by Django 5.1.1 on 2024-10-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0002_photo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публічне фото'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='Cloudinary public_id'),
        ),
    ]
