# Generated by Django 5.1.1 on 2024-10-03 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0003_photo_is_public_alter_photo_public_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='owner',
        ),
    ]
