# Generated by Django 5.1.1 on 2024-10-04 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0004_rename_user_photo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Cloudinary Image URL'),
        ),
    ]
