# Generated by Django 5.1.1 on 2024-10-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0005_photo_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='rating',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Рейтинг фото'),
        ),
    ]
