# Generated by Django 5.1.1 on 2024-10-05 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0006_photo_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг фото'),
        ),
    ]
