# Generated by Django 5.1.1 on 2024-10-05 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_app', '0007_alter_photo_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='rating',
        ),
    ]
