# Generated by Django 5.1.1 on 2024-10-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('WEDDING', 'Wedding Photography'), ('FAMILY_CHILDREN', 'Family and Children Photography'), ('PORTRAIT', 'Portrait Photography'), ('BUSINESS_CORPORATE', 'Business and Corporate Photography'), ('FASHION_MODEL', 'Model and Fashion Photography'), ('EVENT', 'Event Photography'), ('ARCHITECTURAL_INTERIOR', 'Architectural and Interior Photography'), ('FOOD', 'Food Photography'), ('NUDE_ARTISTIC', 'Nude or Artistic Photography'), ('PHOTOJOURNALISM_DOCUMENTARY', 'Photojournalism or Documentary Photography'), ('NATURE_LANDSCAPE', 'Nature and Landscape Photography'), ('SPORTS', 'Sports Photography'), ('AVIATION_AUTOMOTIVE', 'Aviation or Automotive Photography'), ('PET', 'Pet Photography'), ('PANORAMIC_360', '360-Degree and Panoramic Photography'), ('STUDIO', 'Studio Photography'), ('CREATIVE_CONCEPTUAL', 'Creative or Conceptual Photography')], max_length=150, unique=True, verbose_name='Назва'),
        ),
    ]
